//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptBoard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConceptBoard.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap concept_board {
            get {
                object obj = ResourceManager.GetObject("concept_board", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap concept_bulb {
            get {
                object obj = ResourceManager.GetObject("concept_bulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap concept_cube {
            get {
                object obj = ResourceManager.GetObject("concept_cube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap concept_exclamationpoint {
            get {
                object obj = ResourceManager.GetObject("concept_exclamationpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap concept_questionmark {
            get {
                object obj = ResourceManager.GetObject("concept_questionmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101 Dalmations
        ///Air bag
        ///Aircraft carrier
        ///Airport
        ///Aladdin
        ///Ambulance
        ///Angel
        ///Apple
        ///Asprin
        ///Assassin
        ///Attic
        ///Avatar
        ///Banana
        ///Bank
        ///Barbecue
        ///Barbie
        ///Barge
        ///Bat
        ///Bathtub
        ///Bedroom
        ///Bee
        ///Bell
        ///Bike
        ///Binoculars
        ///Booger
        ///Boots
        ///Boxer
        ///Bra
        ///Brick
        ///Bull
        ///Butterfly
        ///Cake
        ///Canary
        ///Canteen
        ///Car stereo
        ///Carpet
        ///Cars
        ///Castle
        ///Cellar
        ///Cellphone
        ///Chainsaw
        ///Chalet
        ///Champagne
        ///Cherry
        ///Chimney
        ///Chocolate
        ///Christmas lights
        ///Church
        ///Cinema
        ///Clown
        ///Coca-Cola
        ///Coconut
        ///Coffee
        ///Computer
        ///Concord
        ///Cow
        ///Crab
        ///Credit card
        ///Crocod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words_easy {
            get {
                return ResourceManager.GetString("words_easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bad check
        ///A good eye for distance
        ///A picture is worth a thousand words
        ///A rolling stone gathers no moss
        ///A Study in Scarlet
        ///Absent-minded
        ///Achilles&apos; Heel
        ///Adam Carolla
        ///Adam Sandler
        ///Add fuel to the fire
        ///Age of Enlightenment
        ///Al Capone
        ///Alcatraz
        ///Ali Baba
        ///American Beauty
        ///An iron fist in a velvet glove
        ///Armed to the teeth
        ///Around the World in 80 Days
        ///Ask for someone&apos;s head
        ///Aziz Ansari
        ///Back to the Future
        ///Bad things always come in threes
        ///Bayoney
        ///Be a third wheel
        ///Be all spruced up
        ///Be crystal clea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words_hard {
            get {
                return ResourceManager.GetString("words_hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2001: A Space Odyssey
        ///A Clockwork Orange
        ///Accountant
        ///Advertisement
        ///Albud Dumbledore
        ///Alf
        ///Allen Ginsberg
        ///Ammo clip
        ///Amy Winehouse
        ///Angry Birds
        ///Animal Planet
        ///Aphrodite
        ///Archimedes
        ///Aspartame
        ///Astro Boy
        ///Atlantis
        ///Atomic bomb
        ///Austin Powers
        ///Bagheera
        ///Baguette
        ///Baker
        ///Baloo
        ///Bambi
        ///Barcode
        ///Batman
        ///Battery
        ///Beach
        ///Beaver
        ///Beer
        ///Beyonce
        ///Bilbo Baggins
        ///Bill Clinton
        ///Billboards
        ///Billy the Kid
        ///Black hole
        ///Bleach
        ///Blowing in the Wind
        ///Bob Marley
        ///Boondock Saints
        ///Borat
        ///Bowling
        ///Bowling for Columbine
        ///Brai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words_medium {
            get {
                return ResourceManager.GetString("words_medium", resourceCulture);
            }
        }
    }
}
